### ISSUE TITLE
Expected field to have list with just 1 item.

### ISSUE THREAD

**Issue by jdnrg** [bluechiptek/cloudhealth-tools#27]
```
chtools perspective get-spec --name XXX > nrg.spec
Traceback (most recent call last):
File "/home/mdupont/.local/share/virtualenvs/clean-gCgXM7hz/bin/chtools", line 11, in <module>
load_entry_point('chtools', 'console_scripts', 'chtools')()
File "sources/cloudhealth-tools/chtools/cli/cli.py", line 84, in main
cli_handler.execute()
File "sources/cloudhealth-tools/chtools/cli/handler.py", line 28, in execute
self._results = method()
File "sources/cloudhealth-tools/chtools/perspective/cli.py", line 83, in _get_spec
results = perspective.spec
File "sources/cloudhealth-tools/chtools/perspective/data.py", line 742, in spec
spec_dict = self._spec_from_schema()
File "sources/cloudhealth-tools/chtools/perspective/data.py", line 440, in _spec_from_schema
"with just 1 item.".format(key, clause)
RuntimeError: Expected field in {'field': ['AwsAccount', 'Example Account Name'], 'op': '=', 'val': 'Example AccountName'} to have list with just 1 item.
```

**Comment by nimbusscale** [comment]
Could you provide the JSON schema for the perspective. You should be able to get the schema with the  following command.

`chtools perspective get-schema --name XXX`
